using System.ComponentModel;
using System.Text;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;
using eneBridge.Wpf.ViewModels;

namespace eneBridge.Wpf;

/// <summary>
/// Interaction logic for MainWindow.xaml
/// </summary>
public partial class MainWindow : Window
{
    // Mirrors the columns ExcelReaderService.ReadIcmaste/ReadIctrane actually populate (see
    // CLAUDE.md's "Most schema columns are intentionally always blank" note). Purely a preview
    // display filter — the exported .dbf files always include the full required schema.
    private static readonly HashSet<string> IcmastePopulatedColumns = new(StringComparer.OrdinalIgnoreCase)
    {
        "TYPE", "ENTRY", "REF", "DATE", "CODE", "NAME", "ACCNO", "USER", "POSTACCNO",
        "CUST2", "CURRCODE", "TAXCODE", "FCRATE", "ADD_COST", "TICK", "BILLAGE",
        "DOWNAMT", "ATMS", "DEPPAID", "EREFUND"
    };

    private static readonly HashSet<string> IctranePopulatedColumns = new(StringComparer.OrdinalIgnoreCase)
    {
        "type", "ref", "item_no", "desc1", "qty", "price", "amount", "taxcode",
        "userid", "entry", "accno", "entry2"
    };

    // Mirrors what ExcelReaderService.ReadStockReceivedIcmaste/ReadStockReceivedIctrane actually
    // populate (see StockReceivedExcelCol and the Stock Received design doc). Same purely-display
    // purpose as IcmastePopulatedColumns/IctranePopulatedColumns above.
    private static readonly HashSet<string> StockReceivedIcmastePopulatedColumns = new(StringComparer.OrdinalIgnoreCase)
    {
        "TYPE", "ENTRY", "REF", "DATE", "CODE", "NAME", "ACCNO", "USER", "POSTACCNO",
        "CUST2", "CURRCODE", "TAXCODE", "VENDNO", "N_AMT", "T_AMT"
    };

    private static readonly HashSet<string> StockReceivedIctranePopulatedColumns = new(StringComparer.OrdinalIgnoreCase)
    {
        "type", "ref", "item_no", "desc1", "qty", "price", "amount", "taxcode", "userid", "entry"
    };

    public MainWindow()
    {
        InitializeComponent();
        DataContextChanged += OnDataContextChanged;

        var version = System.Diagnostics.FileVersionInfo.GetVersionInfo(
            System.Reflection.Assembly.GetExecutingAssembly().Location).ProductVersion;
        Title = $"eneBridge {version}";
    }

    private void ExitButton_Click(object sender, RoutedEventArgs e)
    {
        var result = MessageBox.Show(
            "Are you sure you want to exit?",
            "Confirm Exit",
            MessageBoxButton.YesNo,
            MessageBoxImage.Question);

        if (result == MessageBoxResult.Yes)
        {
            Close();
        }
    }

    private void OnDataContextChanged(object sender, DependencyPropertyChangedEventArgs e)
    {
        if (e.OldValue is MainViewModel oldViewModel)
        {
            oldViewModel.PropertyChanged -= OnViewModelPropertyChanged;
            oldViewModel.StockReceivedViewModel.PropertyChanged -= OnStockReceivedViewModelPropertyChanged;
        }
        if (e.NewValue is MainViewModel newViewModel)
        {
            newViewModel.PropertyChanged += OnViewModelPropertyChanged;
            newViewModel.StockReceivedViewModel.PropertyChanged += OnStockReceivedViewModelPropertyChanged;
        }
    }

    private void OnViewModelPropertyChanged(object? sender, PropertyChangedEventArgs e)
    {
        if (e.PropertyName == nameof(MainViewModel.ShowAllColumns))
        {
            UpdateColumnVisibility(IcmasteGrid, IcmastePopulatedColumns);
            UpdateColumnVisibility(IctraneGrid, IctranePopulatedColumns);
            UpdateColumnVisibility(IcmasteDbfGrid, IcmastePopulatedColumns);
            UpdateColumnVisibility(IctraneDbfGrid, IctranePopulatedColumns);
        }
    }

    private void OnStockReceivedViewModelPropertyChanged(object? sender, PropertyChangedEventArgs e)
    {
        if (e.PropertyName == nameof(StockReceivedViewModel.ShowAllColumns))
        {
            UpdateStockReceivedColumnVisibility(StockReceivedIcmasteGrid, StockReceivedIcmastePopulatedColumns);
            UpdateStockReceivedColumnVisibility(StockReceivedIctraneGrid, StockReceivedIctranePopulatedColumns);
            UpdateStockReceivedColumnVisibility(StockReceivedIcmasteDbfGrid, StockReceivedIcmastePopulatedColumns);
            UpdateStockReceivedColumnVisibility(StockReceivedIctraneDbfGrid, StockReceivedIctranePopulatedColumns);
        }
    }

    private void IcmasteGrid_AutoGeneratedColumns(object sender, EventArgs e) =>
        UpdateColumnVisibility(IcmasteGrid, IcmastePopulatedColumns);

    private void IctraneGrid_AutoGeneratedColumns(object sender, EventArgs e) =>
        UpdateColumnVisibility(IctraneGrid, IctranePopulatedColumns);

    private void IcmasteDbfGrid_AutoGeneratedColumns(object sender, EventArgs e) =>
        UpdateColumnVisibility(IcmasteDbfGrid, IcmastePopulatedColumns);

    private void IctraneDbfGrid_AutoGeneratedColumns(object sender, EventArgs e) =>
        UpdateColumnVisibility(IctraneDbfGrid, IctranePopulatedColumns);

    private void StockReceivedIcmasteGrid_AutoGeneratedColumns(object sender, EventArgs e) =>
        UpdateStockReceivedColumnVisibility(StockReceivedIcmasteGrid, StockReceivedIcmastePopulatedColumns);

    private void StockReceivedIctraneGrid_AutoGeneratedColumns(object sender, EventArgs e) =>
        UpdateStockReceivedColumnVisibility(StockReceivedIctraneGrid, StockReceivedIctranePopulatedColumns);

    private void StockReceivedIcmasteDbfGrid_AutoGeneratedColumns(object sender, EventArgs e) =>
        UpdateStockReceivedColumnVisibility(StockReceivedIcmasteDbfGrid, StockReceivedIcmastePopulatedColumns);

    private void StockReceivedIctraneDbfGrid_AutoGeneratedColumns(object sender, EventArgs e) =>
        UpdateStockReceivedColumnVisibility(StockReceivedIctraneDbfGrid, StockReceivedIctranePopulatedColumns);

    private void UpdateColumnVisibility(DataGrid grid, HashSet<string> populatedColumns)
    {
        bool showAll = DataContext is MainViewModel viewModel && viewModel.ShowAllColumns;
        foreach (var column in grid.Columns)
        {
            column.Visibility = showAll || populatedColumns.Contains(column.SortMemberPath)
                ? Visibility.Visible
                : Visibility.Collapsed;
        }
    }

    private void UpdateStockReceivedColumnVisibility(DataGrid grid, HashSet<string> populatedColumns)
    {
        bool showAll = DataContext is MainViewModel viewModel && viewModel.StockReceivedViewModel.ShowAllColumns;
        foreach (var column in grid.Columns)
        {
            column.Visibility = showAll || populatedColumns.Contains(column.SortMemberPath)
                ? Visibility.Visible
                : Visibility.Collapsed;
        }
    }
}
